apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "threatstack-agent.name" . }}-config-args
  labels:
    app.kubernetes.io/name: {{ include "threatstack-agent.name" . }}
    helm.sh/chart: {{ include "threatstack-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config-args: {{ include "threatstack-agent.docker-config" . }} {{ include "threatstack-agent.containerd-config" . }} {{ .Values.daemonset.additionalRuntimeConfig}}
  kubernetes-api-config-args: enable_kubes_master 1 {{ .Values.apiReader.additionalRuntimeConfig }}
{{- if .Values.daemonset.customAuditRules }}
  custom-audit-rules-content: {{ toYaml .Values.daemonset.customAuditRules | indent 4 }}
{{- end }}
