apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "threatstack-agent.name" .}}
  labels:
    app.kubernetes.io/name: {{ include "threatstack-agent.name" .}}
    helm.sh/chart: {{ include "threatstack-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "threatstack-agent.name" .}}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "threatstack-agent.name" . }}
        helm.sh/chart: {{ include "threatstack-agent.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      name: {{ include "threatstack-agent.name" . }}
      annotations:
      {{- if .Values.daemonset.podAnnotations }}
{{ toYaml .Values.daemonset.podAnnotations | indent 8 }}
      {{- end }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.daemonset.nodeSelector | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.affinity }}
      affinity:
{{ toYaml .Values.daemonset.affinity | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
{{- end }}
      hostNetwork: true
      hostPID: true
      serviceAccountName: {{ if .Values.rbac.create }}{{ include "threatstack-agent.name" . }}{{ else }}{{ .Values.rbac.serviceAccountName }}{{ end }}
      containers:
      - image: {{ .Values.image.repository }}:{{ if not .Values.image.version }}{{ .Chart.AppVersion }}{{ else }}{{ .Values.image.version }}{{ end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "threatstack-agent.name" . }}
{{- if eq .Values.gkeContainerOs true }}
{{ toYaml .Values.gkeContainerOsCmd | indent 8 }}
{{- end }}
{{- if eq .Values.gkeUbuntu true }}
{{ toYaml .Values.gkeUbuntuCmd | indent 8 }}
{{- end }}
{{- if eq .Values.eksAmazon2 true }}
{{ toYaml .Values.eksAmazon2Cmd | indent 8 }}
{{- end }}
{{- if .Values.customDaemonsetCmd }}
{{ toYaml .Values.customDaemonsetCmd | indent 8 }}
{{- end }}
{{- if .Values.daemonset.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.daemonset.livenessProbe | indent 10 }}
{{- else if and (eq .Values.gkeContainerOs false) (eq .Values.gkeUbuntu false) }}
        livenessProbe:
          exec:
            command: [ "sh", "-c", "tsagent status" ]
          initialDelaySeconds: 15
          periodSeconds: 60
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
{{- end }}
        env:
          - name: THREATSTACK_SETUP_ARGS
            valueFrom:
{{- if not .Values.agentSetupExternalSecretRef }}
              secretKeyRef:
                name: {{ include "threatstack-agent.fullname" . }}
                key: ts-setup-args
{{- else }}
              secretKeyRef:
                name: {{ .Values.agentSetupExternalSecretRef.name }}
                key: {{ .Values.agentSetupExternalSecretRef.key }}
{{- end }}
          - name: THREATSTACK_CONFIG_ARGS
            valueFrom:
              configMapKeyRef:
                name: {{ include "threatstack-agent.name" . }}-config-args
                key: config-args
        securityContext:
          privileged: true
          capabilities:
            add: {{ .Values.capabilities | trim }}
{{- if .Values.daemonset.resources }}
        resources:
{{ toYaml .Values.daemonset.resources | trim | indent 10 }}
{{- else }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
{{- end }}
        volumeMounts:
          - name: hostfs
            mountPath: /threatstackfs
          - name: dockersocket
            mountPath: /var/run/docker.sock
          - name: containerdsocket
            mountPath: /run/containerd/containerd.sock
          - name: oldcontainerdsocket
            mountPath: /var/run/docker/containerd/docker-containerd.sock
{{- if .Values.daemonset.customAuditRules }}
          - name: custom-audit-rules
            mountPath: /opt/threatstack/etc/audit-custom.rules
            subPath: audit-custom.rules
{{- end }}
{{- if .Values.daemonset.customTsAuditd }}
          - name: custom-tsauditd-config
            mountPath: /opt/threatstack/etc/tsauditd-custom.cfg
            subPath: tsauditd-custom.cfg
{{- end }}
      volumes:
        - hostPath:
            path: /
          name: hostfs
        - hostPath:
            path: {{ .Values.daemonset.volumes.dockersocket.hostPath }}
          name: dockersocket
        - hostPath:
            path: {{ .Values.daemonset.volumes.containerdsocket.hostPath }}
          name: containerdsocket
        - hostPath:
            path: {{ .Values.daemonset.volumes.oldcontainerdsocket.hostPath }}
          name: oldcontainerdsocket
{{- if .Values.daemonset.customAuditRules }}
        - name: custom-audit-rules
          configMap:
            name: {{ include "threatstack-agent.name" . }}-config-args
            items:
              - key: custom-audit-rules-content
                path: audit-custom.rules
{{- end }}
{{- if .Values.daemonset.customTsAuditd }}
        - name: custom-tsauditd-config
          configMap:
            name: {{ include "threatstack-agent.name" . }}-config-args
            items:
              - key: custom-tsauditd-config
                path: tsauditd-custom.cfg
{{- end }}