# MIT License
#
# Copyright (c) 2020-2023 F5, Inc.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#######
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "threatstack-agent.name" .}}
  labels:
    app.kubernetes.io/name: {{ include "threatstack-agent.name" .}}
    helm.sh/chart: {{ include "threatstack-agent.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "threatstack-agent.name" .}}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "threatstack-agent.name" . }}
        helm.sh/chart: {{ include "threatstack-agent.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
      name: {{ include "threatstack-agent.name" . }}
      annotations:
        # If configmap or secret files change, this will change the checksum annotations in the daemonset, forcing a redeploy.
        # If using an external secret reference, then if external secret name or entry change, but NOT the actual secret data,
        # this will change the checksum annotations in the deployment, forcing a redeploy.
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
{{- if not .Values.agentSetupExternalSecretRef }}
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
{{- else }}
        checksum/secrets: {{ .Values.agentSetupExternalSecretRef | toString | sha256sum }}
{{- end }}
{{- if .Values.daemonset.podAnnotations }}
{{ toYaml .Values.daemonset.podAnnotations | indent 8 }}
{{- end }}
    spec:
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.daemonset.nodeSelector | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.affinity }}
      affinity:
{{ toYaml .Values.daemonset.affinity | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.tolerations }}
      tolerations:
{{ toYaml .Values.daemonset.tolerations | indent 8 }}
{{- else }}
{{- end }}
{{- if .Values.daemonset.priorityClassName }}
      priorityClassName: {{ .Values.daemonset.priorityClassName }}
{{- end }}
      hostNetwork: true
      hostPID: true
      serviceAccountName: {{ include "threatstack-agent.serviceAccountName" . }}
      containers:
      - image: {{ .Values.image.repository }}:{{ if not .Values.image.version }}{{ .Chart.AppVersion }}{{ else }}{{ .Values.image.version }}{{ end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ include "threatstack-agent.name" . }}
{{- if eq .Values.gkeContainerOs true }}
{{ toYaml .Values.gkeContainerOsCmd | indent 8 }}
{{- else if eq .Values.gkeUbuntu true }}
{{ toYaml .Values.gkeUbuntuCmd | indent 8 }}
{{- else if eq .Values.eksAmazon2 true }}
{{ toYaml .Values.eksAmazon2Cmd | indent 8 }}
{{- else if .Values.customDaemonsetCmd }}
{{ toYaml .Values.customDaemonsetCmd | indent 8 }}
{{- else }}
        command: ["bash"]
        args:
          - -c
          - >-
              eval tsagent setup --deploy-key $THREATSTACK_SETUP_DEPLOY_KEY $THREATSTACK_SETUP_ARGS &&
              tsagent config --set $THREATSTACK_CONFIG_ARGS &&
              unset THREATSTACK_SETUP_DEPLOY_KEY THREATSTACK_SETUP_ARGS THREATSTACK_CONFIG_ARGS &&
              exec /opt/threatstack/sbin/tsagentd -logstdout=1
{{- end }}
{{- if .Values.daemonset.livenessProbe }}
        livenessProbe:
{{ toYaml .Values.daemonset.livenessProbe | indent 10 }}
{{- else }}
        livenessProbe:
          exec:
            command: [ "sh", "-c", "tsagent status" ]
          initialDelaySeconds: 15
          periodSeconds: 360
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
{{- end }}
        env:
          - name: THREATSTACK_SETUP_DEPLOY_KEY
            valueFrom:
              secretKeyRef:
{{- if not .Values.agentSetupExternalSecretRef }}
                name: {{ include "threatstack-agent.fullname" . }}
                key: ts-setup-deploy-key
{{- else }}
                name: {{ .Values.agentSetupExternalSecretRef.name }}
                key: {{ .Values.agentSetupExternalSecretRef.key }}
{{- end }}
          - name: THREATSTACK_SETUP_ARGS
            valueFrom:
              configMapKeyRef:
                name: {{ include "threatstack-agent.name" . }}-config-args
                key: setup-args
          - name: THREATSTACK_CONFIG_ARGS
            valueFrom:
              configMapKeyRef:
                name: {{ include "threatstack-agent.name" . }}-config-args
                key: config-args
        securityContext:
          {{- toYaml .Values.daemonset.securityContext | nindent 10 }}
          capabilities:
            add: [{{ include "threatstack-agent.daemonset-capabilities" . | trimSuffix ", " }}]
{{- if .Values.daemonset.resources }}
        resources:
{{ toYaml .Values.daemonset.resources | trim | indent 10 }}
{{- else }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: {{ include "threatstack-agent.daemonset-openshift-default-memlimit" . }}
            cpu: "400m"
{{- end }}
        volumeMounts:
          - name: hostfs
            mountPath: /threatstackfs
            mountPropagation: HostToContainer
            readOnly: true
{{- if .Values.daemonset.customAuditRules }}
          - name: custom-audit-rules
            mountPath: /opt/threatstack/etc/audit-custom.rules
            subPath: audit-custom.rules
{{- end }}
{{- if .Values.daemonset.customTsAuditdConfig }}
          - name: custom-tsauditd-config
            mountPath: /opt/threatstack/etc/tsauditd-custom.cfg
            subPath: tsauditd-custom.cfg
{{- end }}
{{- if .Values.daemonset.customLuaFilter }}
          - name: custom-luafilter-config
            mountPath: /opt/threatstack/etc/tsauditd-custom.lua
            subPath: tsauditd-custom.lua
{{- end }}
{{- if .Values.ebpfEnabled }}
          - name: kernel-debug
            mountPath: /sys/kernel/debug
{{- end }}
      volumes:
        - hostPath:
            path: /
          name: hostfs
{{- if .Values.daemonset.customAuditRules }}
        - name: custom-audit-rules
          configMap:
            name: {{ include "threatstack-agent.name" . }}-config-args
            items:
              - key: custom-audit-rules-content
                path: audit-custom.rules
{{- end }}
{{- if .Values.daemonset.customTsAuditdConfig }}
        - name: custom-tsauditd-config
          configMap:
            name: {{ include "threatstack-agent.name" . }}-config-args
            items:
              - key: custom-tsauditd-config-content
                path: tsauditd-custom.cfg
{{- end }}
{{- if .Values.daemonset.customLuaFilter }}
        - name: custom-luafilter-config
          configMap:
            name: {{ include "threatstack-agent.name" . }}-config-args
            items:
              - key: custom-luafilter-content
                path: tsauditd-custom.lua
{{- end }}
{{- if .Values.ebpfEnabled }}
        - hostPath:
            path: /sys/kernel/debug
          name: kernel-debug
{{- end }}
